package com.jiayaming.dubbo.customer.model;

import java.util.Date;

public class CustomerInfo {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column customer_info.id
	 * @mbg.generated  Sat Feb 10 16:32:41 CST 2018
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column customer_info.uuid
	 * @mbg.generated  Sat Feb 10 16:32:41 CST 2018
	 */
	private String uuid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column customer_info.password
	 * @mbg.generated  Sat Feb 10 16:32:41 CST 2018
	 */
	private String password;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column customer_info.mobile
	 * @mbg.generated  Sat Feb 10 16:32:41 CST 2018
	 */
	private String mobile;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column customer_info.email
	 * @mbg.generated  Sat Feb 10 16:32:41 CST 2018
	 */
	private String email;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column customer_info.nickName
	 * @mbg.generated  Sat Feb 10 16:32:41 CST 2018
	 */
	private String nickname;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column customer_info.name
	 * @mbg.generated  Sat Feb 10 16:32:41 CST 2018
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column customer_info.sex
	 * @mbg.generated  Sat Feb 10 16:32:41 CST 2018
	 */
	private String sex;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column customer_info.solarOrLunar
	 * @mbg.generated  Sat Feb 10 16:32:41 CST 2018
	 */
	private String solarorlunar;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column customer_info.birthday
	 * @mbg.generated  Sat Feb 10 16:32:41 CST 2018
	 */
	private Date birthday;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column customer_info.birthdayTime
	 * @mbg.generated  Sat Feb 10 16:32:41 CST 2018
	 */
	private String birthdaytime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column customer_info.adressProvince
	 * @mbg.generated  Sat Feb 10 16:32:41 CST 2018
	 */
	private String adressprovince;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column customer_info.adressCity
	 * @mbg.generated  Sat Feb 10 16:32:41 CST 2018
	 */
	private String adresscity;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column customer_info.adressCounty
	 * @mbg.generated  Sat Feb 10 16:32:41 CST 2018
	 */
	private String adresscounty;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column customer_info.update_time
	 * @mbg.generated  Sat Feb 10 16:32:41 CST 2018
	 */
	private Date updateTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column customer_info.create_time
	 * @mbg.generated  Sat Feb 10 16:32:41 CST 2018
	 */
	private Date createTime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column customer_info.id
	 * @return  the value of customer_info.id
	 * @mbg.generated  Sat Feb 10 16:32:41 CST 2018
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column customer_info.id
	 * @param id  the value for customer_info.id
	 * @mbg.generated  Sat Feb 10 16:32:41 CST 2018
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column customer_info.uuid
	 * @return  the value of customer_info.uuid
	 * @mbg.generated  Sat Feb 10 16:32:41 CST 2018
	 */
	public String getUuid() {
		return uuid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column customer_info.uuid
	 * @param uuid  the value for customer_info.uuid
	 * @mbg.generated  Sat Feb 10 16:32:41 CST 2018
	 */
	public void setUuid(String uuid) {
		this.uuid = uuid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column customer_info.password
	 * @return  the value of customer_info.password
	 * @mbg.generated  Sat Feb 10 16:32:41 CST 2018
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column customer_info.password
	 * @param password  the value for customer_info.password
	 * @mbg.generated  Sat Feb 10 16:32:41 CST 2018
	 */
	public void setPassword(String password) {
		this.password = password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column customer_info.mobile
	 * @return  the value of customer_info.mobile
	 * @mbg.generated  Sat Feb 10 16:32:41 CST 2018
	 */
	public String getMobile() {
		return mobile;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column customer_info.mobile
	 * @param mobile  the value for customer_info.mobile
	 * @mbg.generated  Sat Feb 10 16:32:41 CST 2018
	 */
	public void setMobile(String mobile) {
		this.mobile = mobile;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column customer_info.email
	 * @return  the value of customer_info.email
	 * @mbg.generated  Sat Feb 10 16:32:41 CST 2018
	 */
	public String getEmail() {
		return email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column customer_info.email
	 * @param email  the value for customer_info.email
	 * @mbg.generated  Sat Feb 10 16:32:41 CST 2018
	 */
	public void setEmail(String email) {
		this.email = email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column customer_info.nickName
	 * @return  the value of customer_info.nickName
	 * @mbg.generated  Sat Feb 10 16:32:41 CST 2018
	 */
	public String getNickname() {
		return nickname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column customer_info.nickName
	 * @param nickname  the value for customer_info.nickName
	 * @mbg.generated  Sat Feb 10 16:32:41 CST 2018
	 */
	public void setNickname(String nickname) {
		this.nickname = nickname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column customer_info.name
	 * @return  the value of customer_info.name
	 * @mbg.generated  Sat Feb 10 16:32:41 CST 2018
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column customer_info.name
	 * @param name  the value for customer_info.name
	 * @mbg.generated  Sat Feb 10 16:32:41 CST 2018
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column customer_info.sex
	 * @return  the value of customer_info.sex
	 * @mbg.generated  Sat Feb 10 16:32:41 CST 2018
	 */
	public String getSex() {
		return sex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column customer_info.sex
	 * @param sex  the value for customer_info.sex
	 * @mbg.generated  Sat Feb 10 16:32:41 CST 2018
	 */
	public void setSex(String sex) {
		this.sex = sex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column customer_info.solarOrLunar
	 * @return  the value of customer_info.solarOrLunar
	 * @mbg.generated  Sat Feb 10 16:32:41 CST 2018
	 */
	public String getSolarorlunar() {
		return solarorlunar;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column customer_info.solarOrLunar
	 * @param solarorlunar  the value for customer_info.solarOrLunar
	 * @mbg.generated  Sat Feb 10 16:32:41 CST 2018
	 */
	public void setSolarorlunar(String solarorlunar) {
		this.solarorlunar = solarorlunar;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column customer_info.birthday
	 * @return  the value of customer_info.birthday
	 * @mbg.generated  Sat Feb 10 16:32:41 CST 2018
	 */
	public Date getBirthday() {
		return birthday;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column customer_info.birthday
	 * @param birthday  the value for customer_info.birthday
	 * @mbg.generated  Sat Feb 10 16:32:41 CST 2018
	 */
	public void setBirthday(Date birthday) {
		this.birthday = birthday;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column customer_info.birthdayTime
	 * @return  the value of customer_info.birthdayTime
	 * @mbg.generated  Sat Feb 10 16:32:41 CST 2018
	 */
	public String getBirthdaytime() {
		return birthdaytime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column customer_info.birthdayTime
	 * @param birthdaytime  the value for customer_info.birthdayTime
	 * @mbg.generated  Sat Feb 10 16:32:41 CST 2018
	 */
	public void setBirthdaytime(String birthdaytime) {
		this.birthdaytime = birthdaytime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column customer_info.adressProvince
	 * @return  the value of customer_info.adressProvince
	 * @mbg.generated  Sat Feb 10 16:32:41 CST 2018
	 */
	public String getAdressprovince() {
		return adressprovince;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column customer_info.adressProvince
	 * @param adressprovince  the value for customer_info.adressProvince
	 * @mbg.generated  Sat Feb 10 16:32:41 CST 2018
	 */
	public void setAdressprovince(String adressprovince) {
		this.adressprovince = adressprovince;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column customer_info.adressCity
	 * @return  the value of customer_info.adressCity
	 * @mbg.generated  Sat Feb 10 16:32:41 CST 2018
	 */
	public String getAdresscity() {
		return adresscity;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column customer_info.adressCity
	 * @param adresscity  the value for customer_info.adressCity
	 * @mbg.generated  Sat Feb 10 16:32:41 CST 2018
	 */
	public void setAdresscity(String adresscity) {
		this.adresscity = adresscity;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column customer_info.adressCounty
	 * @return  the value of customer_info.adressCounty
	 * @mbg.generated  Sat Feb 10 16:32:41 CST 2018
	 */
	public String getAdresscounty() {
		return adresscounty;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column customer_info.adressCounty
	 * @param adresscounty  the value for customer_info.adressCounty
	 * @mbg.generated  Sat Feb 10 16:32:41 CST 2018
	 */
	public void setAdresscounty(String adresscounty) {
		this.adresscounty = adresscounty;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column customer_info.update_time
	 * @return  the value of customer_info.update_time
	 * @mbg.generated  Sat Feb 10 16:32:41 CST 2018
	 */
	public Date getUpdateTime() {
		return updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column customer_info.update_time
	 * @param updateTime  the value for customer_info.update_time
	 * @mbg.generated  Sat Feb 10 16:32:41 CST 2018
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column customer_info.create_time
	 * @return  the value of customer_info.create_time
	 * @mbg.generated  Sat Feb 10 16:32:41 CST 2018
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column customer_info.create_time
	 * @param createTime  the value for customer_info.create_time
	 * @mbg.generated  Sat Feb 10 16:32:41 CST 2018
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}
}