package com.jiayaming.dubbo.customer.model;

import java.util.Date;

public class CustomerInfo {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column customer_info.id
	 * @mbg.generated  Mon Feb 26 09:26:25 CST 2018
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column customer_info.uuid
	 * @mbg.generated  Mon Feb 26 09:26:25 CST 2018
	 */
	private String uuid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column customer_info.password
	 * @mbg.generated  Mon Feb 26 09:26:25 CST 2018
	 */
	private String password;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column customer_info.mobile
	 * @mbg.generated  Mon Feb 26 09:26:25 CST 2018
	 */
	private String mobile;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column customer_info.email
	 * @mbg.generated  Mon Feb 26 09:26:25 CST 2018
	 */
	private String email;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column customer_info.nick_name
	 * @mbg.generated  Mon Feb 26 09:26:25 CST 2018
	 */
	private String nickName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column customer_info.name
	 * @mbg.generated  Mon Feb 26 09:26:25 CST 2018
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column customer_info.sex
	 * @mbg.generated  Mon Feb 26 09:26:25 CST 2018
	 */
	private String sex;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column customer_info.solar_or_lunar
	 * @mbg.generated  Mon Feb 26 09:26:25 CST 2018
	 */
	private String solarOrLunar;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column customer_info.birthday
	 * @mbg.generated  Mon Feb 26 09:26:25 CST 2018
	 */
	private Date birthday;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column customer_info.birthday_time
	 * @mbg.generated  Mon Feb 26 09:26:25 CST 2018
	 */
	private String birthdayTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column customer_info.adress_province
	 * @mbg.generated  Mon Feb 26 09:26:25 CST 2018
	 */
	private String adressProvince;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column customer_info.adress_city
	 * @mbg.generated  Mon Feb 26 09:26:25 CST 2018
	 */
	private String adressCity;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column customer_info.adress_county
	 * @mbg.generated  Mon Feb 26 09:26:25 CST 2018
	 */
	private String adressCounty;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column customer_info.customer_type
	 * @mbg.generated  Mon Feb 26 09:26:25 CST 2018
	 */
	private String customerType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column customer_info.last_login_date
	 * @mbg.generated  Mon Feb 26 09:26:25 CST 2018
	 */
	private Date lastLoginDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column customer_info.update_time
	 * @mbg.generated  Mon Feb 26 09:26:25 CST 2018
	 */
	private Date updateTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column customer_info.create_time
	 * @mbg.generated  Mon Feb 26 09:26:25 CST 2018
	 */
	private Date createTime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column customer_info.id
	 * @return  the value of customer_info.id
	 * @mbg.generated  Mon Feb 26 09:26:25 CST 2018
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column customer_info.id
	 * @param id  the value for customer_info.id
	 * @mbg.generated  Mon Feb 26 09:26:25 CST 2018
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column customer_info.uuid
	 * @return  the value of customer_info.uuid
	 * @mbg.generated  Mon Feb 26 09:26:25 CST 2018
	 */
	public String getUuid() {
		return uuid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column customer_info.uuid
	 * @param uuid  the value for customer_info.uuid
	 * @mbg.generated  Mon Feb 26 09:26:25 CST 2018
	 */
	public void setUuid(String uuid) {
		this.uuid = uuid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column customer_info.password
	 * @return  the value of customer_info.password
	 * @mbg.generated  Mon Feb 26 09:26:25 CST 2018
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column customer_info.password
	 * @param password  the value for customer_info.password
	 * @mbg.generated  Mon Feb 26 09:26:25 CST 2018
	 */
	public void setPassword(String password) {
		this.password = password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column customer_info.mobile
	 * @return  the value of customer_info.mobile
	 * @mbg.generated  Mon Feb 26 09:26:25 CST 2018
	 */
	public String getMobile() {
		return mobile;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column customer_info.mobile
	 * @param mobile  the value for customer_info.mobile
	 * @mbg.generated  Mon Feb 26 09:26:25 CST 2018
	 */
	public void setMobile(String mobile) {
		this.mobile = mobile;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column customer_info.email
	 * @return  the value of customer_info.email
	 * @mbg.generated  Mon Feb 26 09:26:25 CST 2018
	 */
	public String getEmail() {
		return email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column customer_info.email
	 * @param email  the value for customer_info.email
	 * @mbg.generated  Mon Feb 26 09:26:25 CST 2018
	 */
	public void setEmail(String email) {
		this.email = email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column customer_info.nick_name
	 * @return  the value of customer_info.nick_name
	 * @mbg.generated  Mon Feb 26 09:26:25 CST 2018
	 */
	public String getNickName() {
		return nickName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column customer_info.nick_name
	 * @param nickName  the value for customer_info.nick_name
	 * @mbg.generated  Mon Feb 26 09:26:25 CST 2018
	 */
	public void setNickName(String nickName) {
		this.nickName = nickName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column customer_info.name
	 * @return  the value of customer_info.name
	 * @mbg.generated  Mon Feb 26 09:26:25 CST 2018
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column customer_info.name
	 * @param name  the value for customer_info.name
	 * @mbg.generated  Mon Feb 26 09:26:25 CST 2018
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column customer_info.sex
	 * @return  the value of customer_info.sex
	 * @mbg.generated  Mon Feb 26 09:26:25 CST 2018
	 */
	public String getSex() {
		return sex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column customer_info.sex
	 * @param sex  the value for customer_info.sex
	 * @mbg.generated  Mon Feb 26 09:26:25 CST 2018
	 */
	public void setSex(String sex) {
		this.sex = sex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column customer_info.solar_or_lunar
	 * @return  the value of customer_info.solar_or_lunar
	 * @mbg.generated  Mon Feb 26 09:26:25 CST 2018
	 */
	public String getSolarOrLunar() {
		return solarOrLunar;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column customer_info.solar_or_lunar
	 * @param solarOrLunar  the value for customer_info.solar_or_lunar
	 * @mbg.generated  Mon Feb 26 09:26:25 CST 2018
	 */
	public void setSolarOrLunar(String solarOrLunar) {
		this.solarOrLunar = solarOrLunar;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column customer_info.birthday
	 * @return  the value of customer_info.birthday
	 * @mbg.generated  Mon Feb 26 09:26:25 CST 2018
	 */
	public Date getBirthday() {
		return birthday;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column customer_info.birthday
	 * @param birthday  the value for customer_info.birthday
	 * @mbg.generated  Mon Feb 26 09:26:25 CST 2018
	 */
	public void setBirthday(Date birthday) {
		this.birthday = birthday;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column customer_info.birthday_time
	 * @return  the value of customer_info.birthday_time
	 * @mbg.generated  Mon Feb 26 09:26:25 CST 2018
	 */
	public String getBirthdayTime() {
		return birthdayTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column customer_info.birthday_time
	 * @param birthdayTime  the value for customer_info.birthday_time
	 * @mbg.generated  Mon Feb 26 09:26:25 CST 2018
	 */
	public void setBirthdayTime(String birthdayTime) {
		this.birthdayTime = birthdayTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column customer_info.adress_province
	 * @return  the value of customer_info.adress_province
	 * @mbg.generated  Mon Feb 26 09:26:25 CST 2018
	 */
	public String getAdressProvince() {
		return adressProvince;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column customer_info.adress_province
	 * @param adressProvince  the value for customer_info.adress_province
	 * @mbg.generated  Mon Feb 26 09:26:25 CST 2018
	 */
	public void setAdressProvince(String adressProvince) {
		this.adressProvince = adressProvince;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column customer_info.adress_city
	 * @return  the value of customer_info.adress_city
	 * @mbg.generated  Mon Feb 26 09:26:25 CST 2018
	 */
	public String getAdressCity() {
		return adressCity;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column customer_info.adress_city
	 * @param adressCity  the value for customer_info.adress_city
	 * @mbg.generated  Mon Feb 26 09:26:25 CST 2018
	 */
	public void setAdressCity(String adressCity) {
		this.adressCity = adressCity;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column customer_info.adress_county
	 * @return  the value of customer_info.adress_county
	 * @mbg.generated  Mon Feb 26 09:26:25 CST 2018
	 */
	public String getAdressCounty() {
		return adressCounty;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column customer_info.adress_county
	 * @param adressCounty  the value for customer_info.adress_county
	 * @mbg.generated  Mon Feb 26 09:26:25 CST 2018
	 */
	public void setAdressCounty(String adressCounty) {
		this.adressCounty = adressCounty;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column customer_info.customer_type
	 * @return  the value of customer_info.customer_type
	 * @mbg.generated  Mon Feb 26 09:26:25 CST 2018
	 */
	public String getCustomerType() {
		return customerType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column customer_info.customer_type
	 * @param customerType  the value for customer_info.customer_type
	 * @mbg.generated  Mon Feb 26 09:26:25 CST 2018
	 */
	public void setCustomerType(String customerType) {
		this.customerType = customerType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column customer_info.last_login_date
	 * @return  the value of customer_info.last_login_date
	 * @mbg.generated  Mon Feb 26 09:26:25 CST 2018
	 */
	public Date getLastLoginDate() {
		return lastLoginDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column customer_info.last_login_date
	 * @param lastLoginDate  the value for customer_info.last_login_date
	 * @mbg.generated  Mon Feb 26 09:26:25 CST 2018
	 */
	public void setLastLoginDate(Date lastLoginDate) {
		this.lastLoginDate = lastLoginDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column customer_info.update_time
	 * @return  the value of customer_info.update_time
	 * @mbg.generated  Mon Feb 26 09:26:25 CST 2018
	 */
	public Date getUpdateTime() {
		return updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column customer_info.update_time
	 * @param updateTime  the value for customer_info.update_time
	 * @mbg.generated  Mon Feb 26 09:26:25 CST 2018
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column customer_info.create_time
	 * @return  the value of customer_info.create_time
	 * @mbg.generated  Mon Feb 26 09:26:25 CST 2018
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column customer_info.create_time
	 * @param createTime  the value for customer_info.create_time
	 * @mbg.generated  Mon Feb 26 09:26:25 CST 2018
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}
}