package com.jiayaming.dubbo.customer.model;

import java.util.Date;

public class Test01 {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test01.id
     *
     * @mbg.generated Thu Feb 08 16:47:39 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test01.name
     *
     * @mbg.generated Thu Feb 08 16:47:39 CST 2018
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test01.update_time
     *
     * @mbg.generated Thu Feb 08 16:47:39 CST 2018
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test01.create_time
     *
     * @mbg.generated Thu Feb 08 16:47:39 CST 2018
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test01.id
     *
     * @return the value of test01.id
     *
     * @mbg.generated Thu Feb 08 16:47:39 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test01.id
     *
     * @param id the value for test01.id
     *
     * @mbg.generated Thu Feb 08 16:47:39 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test01.name
     *
     * @return the value of test01.name
     *
     * @mbg.generated Thu Feb 08 16:47:39 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test01.name
     *
     * @param name the value for test01.name
     *
     * @mbg.generated Thu Feb 08 16:47:39 CST 2018
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test01.update_time
     *
     * @return the value of test01.update_time
     *
     * @mbg.generated Thu Feb 08 16:47:39 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test01.update_time
     *
     * @param updateTime the value for test01.update_time
     *
     * @mbg.generated Thu Feb 08 16:47:39 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test01.create_time
     *
     * @return the value of test01.create_time
     *
     * @mbg.generated Thu Feb 08 16:47:39 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test01.create_time
     *
     * @param createTime the value for test01.create_time
     *
     * @mbg.generated Thu Feb 08 16:47:39 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}