package com.jiayaming.dubbo.customer.dao;

import com.jiayaming.dubbo.customer.model.Test01;

public interface Test01Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test01
     *
     * @mbg.generated Thu Feb 08 16:47:39 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test01
     *
     * @mbg.generated Thu Feb 08 16:47:39 CST 2018
     */
    int insert(Test01 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test01
     *
     * @mbg.generated Thu Feb 08 16:47:39 CST 2018
     */
    int insertSelective(Test01 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test01
     *
     * @mbg.generated Thu Feb 08 16:47:39 CST 2018
     */
    Test01 selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test01
     *
     * @mbg.generated Thu Feb 08 16:47:39 CST 2018
     */
    int updateByPrimaryKeySelective(Test01 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test01
     *
     * @mbg.generated Thu Feb 08 16:47:39 CST 2018
     */
    int updateByPrimaryKey(Test01 record);
}